### ISSUE TITLE
Update broke this

### ISSUE THREAD

**Issue by JulianusIV** [Overimagine1/old-discord-font#8]
A recent discord update broke this, will it be updated again at some time soon?

**Comment by Overimagine1** [comment]
It works fine for me on Vencord. What client mod are you using?

**Comment by treacherousfiend** [comment]
Personally, I'm using openasar and its very finicky, for some reason import URLs only seem to work some of the time. I think I saw someone mention it was due to a change in the cross-site data policy or something, but I really don't know much about it or if it can be fixed, at least on a theme creator's end

**Comment by Overimagine1** [comment]
closing as inactive/cant reproduce
